# kics-scan disable=fd54f200-402c-4333-a5a4-36ef6709af2f
FROM cyberark/ubuntu-ruby-builder:latest AS builder

ARG CONJUR_HOME=/src/opt/conjur/possum

WORKDIR ${CONJUR_HOME}

COPY . .

RUN bundle config set --local without 'test development' && \
    bundle config set --local deployment true && \
    bundle config set --local path vendor/bundle && \
    bundle config --local jobs "$(nproc --all)" && \
    bundle install && \
    # Remove private keys brought in by gems in their test data
    find / -name 'openid_connect-*' -type d -exec find {} -name '*.pem' -type f -delete \; && \
    find / -name 'httpclient-*' -type d -exec find {} -name '*.key' -type f -delete \; && \
    find / -name 'httpclient-*' -type d -exec find {} -name '*.pem' -type f -delete \;

# Cleanup any plugin data from bundle
RUN rm -rf .bundle/plugin

FROM alpine:latest

ARG CONJUR_HOME=/src/opt/conjur/possum

WORKDIR /src

COPY --from=builder ${CONJUR_HOME} ${CONJUR_HOME}

RUN mkdir -p usr/local/bin
RUN ln -sf /opt/conjur/possum/bin/conjur-possum usr/local/bin/

RUN mkdir -p etc/conjur/nginx.d
COPY distrib/nginx/* etc/conjur/nginx.d/

RUN mkdir -p etc/service/conjur/possum/log
RUN ln -sf /etc/service/conjur/plugin-service etc/service/conjur/possum/run
RUN ln -sf /etc/service/conjur/plugin-logger  etc/service/conjur/possum/log/run

RUN mkdir -p opt/conjur/etc
COPY distrib/conjur/etc/* opt/conjur/etc/

RUN mkdir -p opt/conjur/possum/config
RUN rm -r opt/conjur/possum/distrib
