FROM ruby:3.4-slim

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
RUN gem update --system --no-document
RUN gem install -N conjur-api --version 6.1.0
RUN gem install -N sinatra
RUN gem install -N rackup puma

COPY inventory.rb usr/src/inventory.rb

ENV PORT 80

CMD [ "ruby", "/usr/src/inventory.rb" ]
